spring:
  datasource:
    url: "jdbc:mysql://192.168.124.142:3308/ratings"
    username: "admin"
    password: "password"
  cloud:
    stream:
      bindings:
        bookmarkDeletions:
          group: ratings
server.port: 9095
