
eureka:
  instance:
    instance-id: '${spring.application.name}:${random.value}'
    preferIpAddress: true
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
spring:
  jackson:
    serialization:
      indent-output: true
  redis:
    host: 192.168.124.142
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    username: 'admin'
    password: 'password'
    addresses: 192.168.124.142
    port: 5672
  sleuth.sampler.probability: 0.9
  cloud:
    config:
      #otherwise the clients would lead to a lot of logging and load on the configserver
      server.health.enabled: false
      #otherwise we can't override the port via command line args
      overrideSystemProperties: false

server:
  use-forward-headers: true



#logging.level:
#  org.springframework.web: DEBUG
#  com.riccio: DEBUG

